Traceback (most recent call last):
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# download file headers and report file size
file_size(DATA_URL)

# download the file...(only needs to be done once).
print('downloading =>', end=' ')
response = requests.get(DATA_URL)

if response.status_code == RESPONSE_SUCCESS:
    print('successful')

    # write to file
    with open(CLEAN_ARCHIVE_NAME, 'wb') as f:
        f.write(response.content)
else:
    print('file not found.')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m [38;5;66;03m# download file headers and report file size[39;00m
[0;32m----> 2[0m [43mfile_size[49m[43m([49m[43mDATA_URL[49m[43m)[49m
[1;32m      4[0m [38;5;66;03m# download the file...(only needs to be done once).[39;00m
[1;32m      5[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mdownloading =>[39m[38;5;124m'[39m, end[38;5;241m=[39m[38;5;124m'[39m[38;5;124m [39m[38;5;124m'[39m)

Cell [0;32mIn[3], line 66[0m, in [0;36mfile_size[0;34m(url)[0m
[1;32m     64[0m response [38;5;241m=[39m requests[38;5;241m.[39mhead(url)
[1;32m     65[0m conversion [38;5;241m=[39m [38;5;241m1_000_000[39m
[0;32m---> 66[0m fsize [38;5;241m=[39m [38;5;28mfloat[39m([43mresponse[49m[38;5;241;43m.[39;49m[43mheaders[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mContent-Length[39;49m[38;5;124;43m'[39;49m[43m][49m) [38;5;241m/[39m conversion
[1;32m     67[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mFile size: [39m[38;5;132;01m{[39;00mfsize[38;5;132;01m:[39;00m[38;5;124m.1f[39m[38;5;132;01m}[39;00m[38;5;124m MB[39m[38;5;124m'[39m)

File [0;32m~/miniforge3/envs/hds_code/lib/python3.11/site-packages/requests/structures.py:52[0m, in [0;36mCaseInsensitiveDict.__getitem__[0;34m(self, key)[0m
[1;32m     51[0m [38;5;28;01mdef[39;00m [38;5;21m__getitem__[39m([38;5;28mself[39m, key):
[0;32m---> 52[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_store[49m[43m[[49m[43mkey[49m[38;5;241;43m.[39;49m[43mlower[49m[43m([49m[43m)[49m[43m][49m[[38;5;241m1[39m]

[0;31mKeyError[0m: 'content-length'

