Traceback (most recent call last):
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tom/miniforge3/envs/hds_code/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

b = np.array([1, 2])

print(a.shape)
print(b.shape)

a + b
------------------

----- stdout -----
(4, 3)
(2,)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[8], line 11[0m
[1;32m      8[0m [38;5;28mprint[39m(a[38;5;241m.[39mshape)
[1;32m      9[0m [38;5;28mprint[39m(b[38;5;241m.[39mshape)
[0;32m---> 11[0m [43ma[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43mb[49m

[0;31mValueError[0m: operands could not be broadcast together with shapes (4,3) (2,) 

